FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY streamlit_app /streamlit_app

EXPOSE 8501

CMD ["streamlit", "run", "/streamlit_app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
