"""add_file_hash_and_pending_status

Revision ID: 2b4e32947dfb
Revises: 8d29da1be0c7
Create Date: 2026-03-26 21:13:58.306518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

# revision identifiers, used by Alembic.
revision: str = '2b4e32947dfb'
down_revision: Union[str, None] = '8d29da1be0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###