"""add_file_hash_and_pending_status

Revision ID: 8d29da1be0c7
Revises: 001_initial
Create Date: 2026-03-26 21:10:38.531024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d29da1be0c7'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.alter_column('document_pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.alter_column('documents', 'fraud_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('documents_document_number_key', 'documents', type_='unique')
    op.drop_index('ix_documents_document_number', table_name='documents')
    op.create_index(op.f('ix_documents_document_number'), 'documents', ['document_number'], unique=True)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.alter_column('dosare', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('dosare', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('dosare', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('dosare_dosar_number_key', 'dosare', type_='unique')
    op.drop_index('ix_dosare_dosar_number', table_name='dosare')
    op.create_index(op.f('ix_dosare_dosar_number'), 'dosare', ['dosar_number'], unique=True)
    op.alter_column('extracted_data', 'extraction_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('extracted_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('extracted_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('fraud_alerts', sa.Column('fraud_score', sa.Float(), nullable=False))
    op.add_column('fraud_alerts', sa.Column('risk_level', sa.String(length=20), nullable=False))
    op.add_column('fraud_alerts', sa.Column('is_resolved', sa.Integer(), nullable=True))
    op.add_column('fraud_alerts', sa.Column('resolution_notes', sa.Text(), nullable=True))
    op.add_column('fraud_alerts', sa.Column('detected_at', sa.DateTime(), nullable=True))
    op.add_column('fraud_alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.alter_column('fraud_alerts', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_fraud_alerts_detected_at'), 'fraud_alerts', ['detected_at'], unique=False)
    op.drop_constraint('fraud_alerts_reviewed_by_id_fkey', 'fraud_alerts', type_='foreignkey')
    op.drop_column('fraud_alerts', 'is_reviewed')
    op.drop_column('fraud_alerts', 'created_at')
    op.drop_column('fraud_alerts', 'reviewed_by_id')
    op.drop_column('fraud_alerts', 'severity')
    op.drop_column('fraud_alerts', 'score')
    op.drop_column('fraud_alerts', 'reviewed_at')
    op.alter_column('nomenclator', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('nomenclator', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('nomenclator', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('nomenclator_code_key', 'nomenclator', type_='unique')
    op.drop_index('ix_nomenclator_code', table_name='nomenclator')
    op.create_index(op.f('ix_nomenclator_code'), 'nomenclator', ['code'], unique=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_nomenclator_code'), table_name='nomenclator')
    op.create_index('ix_nomenclator_code', 'nomenclator', ['code'], unique=False)
    op.create_unique_constraint('nomenclator_code_key', 'nomenclator', ['code'])
    op.alter_column('nomenclator', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('nomenclator', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('nomenclator', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.add_column('fraud_alerts', sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('fraud_alerts', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('fraud_alerts', sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('fraud_alerts', sa.Column('reviewed_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fraud_alerts', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('fraud_alerts', sa.Column('is_reviewed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key('fraud_alerts_reviewed_by_id_fkey', 'fraud_alerts', 'users', ['reviewed_by_id'], ['id'])
    op.drop_index(op.f('ix_fraud_alerts_detected_at'), table_name='fraud_alerts')
    op.alter_column('fraud_alerts', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('fraud_alerts', 'resolved_at')
    op.drop_column('fraud_alerts', 'detected_at')
    op.drop_column('fraud_alerts', 'resolution_notes')
    op.drop_column('fraud_alerts', 'is_resolved')
    op.drop_column('fraud_alerts', 'risk_level')
    op.drop_column('fraud_alerts', 'fraud_score')
    op.alter_column('extracted_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('extracted_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('extracted_data', 'extraction_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.drop_index(op.f('ix_dosare_dosar_number'), table_name='dosare')
    op.create_index('ix_dosare_dosar_number', 'dosare', ['dosar_number'], unique=False)
    op.create_unique_constraint('dosare_dosar_number_key', 'dosare', ['dosar_number'])
    op.alter_column('dosare', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('dosare', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('dosare', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_number'), table_name='documents')
    op.create_index('ix_documents_document_number', 'documents', ['document_number'], unique=False)
    op.create_unique_constraint('documents_document_number_key', 'documents', ['document_number'])
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('documents', 'fraud_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_column('documents', 'file_hash')
    op.alter_column('document_pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###