"""ghost_busted

Revision ID: a1c4e6263032
Revises: 
Create Date: 2026-03-30 21:07:41.277558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c4e6263032'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nomenclator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('default_termen_pastrare', sa.Enum('SIX_MONTHS', 'ONE_YEAR', 'THREE_YEARS', 'FIVE_YEARS', 'SEVEN_YEARS', 'TEN_YEARS', 'PERMANENT', name='pastrareenum'), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['nomenclator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomenclator_code'), 'nomenclator', ['code'], unique=True)
    op.create_index(op.f('ix_nomenclator_id'), 'nomenclator', ['id'], unique=False)
    op.create_index(op.f('ix_nomenclator_parent_id'), 'nomenclator', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ARCHIVIST', 'INSPECTOR', 'VIEWER', 'SYSTEM', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dosare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dosar_number', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=511), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nomenclator_id', sa.Integer(), nullable=False),
    sa.Column('termen_pastrare', sa.Enum('SIX_MONTHS', 'ONE_YEAR', 'THREE_YEARS', 'FIVE_YEARS', 'SEVEN_YEARS', 'TEN_YEARS', 'PERMANENT', name='pastrareenum'), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nomenclator_id'], ['nomenclator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dosare_dosar_number'), 'dosare', ['dosar_number'], unique=True)
    op.create_index(op.f('ix_dosare_id'), 'dosare', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('INVOICE', 'CONTRACT', 'REPORT', 'CORRESPONDENCE', 'DECISION', 'PROTOCOL', 'OTHER', 'ADRESA', 'CERERE', 'HCL', 'DEVIZ', name='documenttypeenum'), nullable=False),
    sa.Column('title', sa.String(length=511), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('file_path', sa.String(length=511), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'PROCESSING', 'CLASSIFIED', 'EXTRACTED', 'VALIDATED', 'ARCHIVED', 'REJECTED', name='documentstatusenum'), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('dosar_id', sa.Integer(), nullable=True),
    sa.Column('nomenclator_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dosar_id'], ['dosare.id'], ),
    sa.ForeignKeyConstraint(['nomenclator_id'], ['nomenclator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_number'), 'documents', ['document_number'], unique=True)
    op.create_index(op.f('ix_documents_dosar_id'), 'documents', ['dosar_id'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'DOWNLOAD', 'UPLOAD', 'CLASSIFY', 'EXTRACT', 'ARCHIVE', 'RESTORE', 'LOGIN', 'LOGOUT', 'PERMISSION_CHANGE', name='auditactionenum'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=511), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_id'), 'document_pages', ['id'], unique=False)
    op.create_table('extracted_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_data_document_id'), 'extracted_data', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_data_id'), 'extracted_data', ['id'], unique=False)
    op.create_table('fraud_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.Enum('DUPLICATE_DOCUMENT', 'FORGED_SIGNATURE', 'TAMPERED_DATA', 'INVALID_AMOUNT', 'PATTERN_ANOMALY', 'MISSING_METADATA', 'OCR_ERROR', 'UNKNOWN', name='anomalytypeenum'), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_alerts_detected_at'), 'fraud_alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_document_id'), 'fraud_alerts', ['document_id'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_id'), 'fraud_alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_alerts_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_document_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_detected_at'), table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    op.drop_index(op.f('ix_extracted_data_id'), table_name='extracted_data')
    op.drop_index(op.f('ix_extracted_data_document_id'), table_name='extracted_data')
    op.drop_table('extracted_data')
    op.drop_index(op.f('ix_document_pages_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_dosar_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_number'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_dosare_id'), table_name='dosare')
    op.drop_index(op.f('ix_dosare_dosar_number'), table_name='dosare')
    op.drop_table('dosare')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_nomenclator_parent_id'), table_name='nomenclator')
    op.drop_index(op.f('ix_nomenclator_id'), table_name='nomenclator')
    op.drop_index(op.f('ix_nomenclator_code'), table_name='nomenclator')
    op.drop_table('nomenclator')
    # ### end Alembic commands ###