"""Add missing document fields

Revision ID: c183b94ea2f1
Revises: bf8f1c9e2a7c
Create Date: 2026-04-11 15:38:14.059035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c183b94ea2f1'
down_revision: Union[str, None] = 'bf8f1c9e2a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###